Remove PCF2131 patch reference from kernel recipe
Kernel 6.6+ in LmP v95.2 has native PCF2131 support, so our custom
patch is no longer needed and was causing build failures:

ERROR: Unable to get checksum for linux-lmp-fslc-imx SRC_URI entry
0007-rtc-pcf2127-add-support-for-PCF2131-RTC.patch: file could not be found

Removed the patch reference but kept pcf2131-rtc.cfg which enables
the native PCF2127 driver (supports PCF2131) as a module.